/* Display the supplied original plans without rebuilding their text or arrows. */
let planViewerCleanup=null;
const savedPlanViews=new Map();
function showPlan(index){
 const data=INTERACTIVE_PLANS[index],name=DATA.majors[index];if(!name||!data)return;
 openPanel(name,'الخطة الشجرية',`<div class="original-plan-toolbar"><div class="original-plan-controls"><button type="button" data-image-zoom="out" aria-label="تصغير">−</button><output id="planZoomValue">100٪</output><button type="button" data-image-zoom="in" aria-label="تكبير">+</button><button type="button" data-image-zoom="fit">عرض كامل</button><button type="button" data-image-zoom="read">حجم القراءة</button></div></div><p class="original-plan-help">اضغط المادة لفتح ملفاتها · اسحب للتنقل · كبّر بإصبعين أو بالأزرار</p><div class="original-plan-view" id="originalPlanView" tabindex="0" aria-label="الخطة الشجرية لتخصص ${escapeHTML(name)}"><div id="originalPlanImage" class="digital-plan-stage" style="width:${data.width}px;height:${data.height}px">${renderDigitalPlan(data,index)}</div><div class="plan-image-status" id="planImageStatus">جارٍ تحميل الخطة…</div></div>`);
 $('.panel').classList.add('plan-panel','original-plan-panel');
 const view=$('#originalPlanView'),img=$('#originalPlanImage'),status=$('#planImageStatus'),output=$('#planZoomValue'),abort=new AbortController(),pointers=new Map();let scale=1,x=0,y=0,fitScale=1,previous=null,loaded=false,dragMoved=false,downPoint=null,frame=0;
 const apply=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{img.style.transform=`translate(${x}px,${y}px) scale(${scale})`;output.textContent=Math.round(scale*100)+'٪'});};
 const zoom=(next,px=view.clientWidth/2,py=view.clientHeight/2)=>{if(!loaded)return;next=Math.max(fitScale,Math.min(3,next));x=px-(px-x)*next/scale;y=py-(py-y)*next/scale;scale=next;apply()};
 const fit=()=>{if(!loaded)return;fitScale=Math.min((view.clientWidth-16)/data.width,(view.clientHeight-16)/data.height,1);scale=fitScale;x=(view.clientWidth-data.width*scale)/2;y=(view.clientHeight-data.height*scale)/2;apply()};
 const listen=(target,type,fn,options={})=>target.addEventListener(type,fn,{...options,signal:abort.signal});
 listen(img,'load',()=>{loaded=true;status.hidden=true;fit()});listen(img,'error',()=>status.textContent='تعذّر تحميل الخطة. أعد فتحها وحاول مجددًا.');
 const gesture=()=>{const p=[...pointers.values()];if(p.length>=2)return {x:(p[0].x+p[1].x)/2,y:(p[0].y+p[1].y)/2,d:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y),two:true};return p.length?{...p[0],two:false}:null};
 listen(view,'pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();if(!pointers.size){dragMoved=false;downPoint={x:e.clientX,y:e.clientY}}view.focus();view.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});previous=gesture();view.classList.add('dragging')});
 listen(view,'pointermove',e=>{if(!pointers.has(e.pointerId))return;if(downPoint&&Math.hypot(e.clientX-downPoint.x,e.clientY-downPoint.y)>7)dragMoved=true;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const next=gesture();if(next?.two)dragMoved=true;if(previous&&next&&previous.two===next.two){if(next.two&&previous.d>0){const r=view.getBoundingClientRect();zoom(scale*next.d/previous.d,previous.x-r.left,previous.y-r.top)}x+=next.x-previous.x;y+=next.y-previous.y;apply()}previous=next});
 const end=e=>{pointers.delete(e.pointerId);previous=gesture();if(!pointers.size)view.classList.remove('dragging')};listen(view,'pointerup',end);listen(view,'pointercancel',end);listen(view,'lostpointercapture',end);
 listen(view,'wheel',e=>{e.preventDefault();const r=view.getBoundingClientRect();zoom(scale*(e.deltaY<0?1.12:1/1.12),e.clientX-r.left,e.clientY-r.top)},{passive:false});
 listen(view,'dblclick',e=>{const r=view.getBoundingClientRect();zoom(scale<.8?.8:fitScale,e.clientX-r.left,e.clientY-r.top)});
 listen(view,'keydown',e=>{if(e.key==='+'||e.key==='=')zoom(scale*1.2);else if(e.key==='-')zoom(scale/1.2);else if(e.key==='0')fit();else if(e.key==='ArrowLeft')x+=40;else if(e.key==='ArrowRight')x-=40;else if(e.key==='ArrowUp')y+=40;else if(e.key==='ArrowDown')y-=40;else return;e.preventDefault();apply()});
 ['copy','cut','contextmenu','dragstart','selectstart'].forEach(type=>listen(view,type,e=>e.preventDefault()));
 document.querySelectorAll('[data-image-zoom]').forEach(button=>listen(button,'click',()=>{const action=button.dataset.imageZoom;if(action==='fit')fit();else if(action==='read')zoom(Math.max(.65,fitScale));else zoom(scale*(action==='in'?1.2:1/1.2))}));
 listen(view,'click',e=>{const button=e.target.closest('[data-plan-course]');if(button&&!dragMoved)openPlanMaterial(index,button.dataset.planCourse)});const observer=new ResizeObserver(()=>{if(!loaded)return;fitScale=Math.min((view.clientWidth-16)/data.width,(view.clientHeight-16)/data.height,1);if(scale<fitScale)fit();else apply()});observer.observe(view);planViewerCleanup=()=>{savedPlanViews.set(index,{scale,x,y});abort.abort();observer.disconnect();pointers.clear();cancelAnimationFrame(frame);planViewerCleanup=null};loaded=true;status.hidden=true;fit();const saved=savedPlanViews.get(index);if(saved){scale=Math.max(fitScale,saved.scale);x=saved.x;y=saved.y;apply()}else if(view.clientWidth<650){scale=Math.max(fitScale,.72);x=view.clientWidth-data.width*scale-8;y=16;apply()}
}

function renderDigitalPlan(data,index){const colors=['#ad6cff','#f5ad35','#54a8ff','#42d79c'],accent=colors[index],nodes=new Map(data.nodes.map(n=>[n.id,n]));const lines=data.edges.map((edge,i)=>{const a=nodes.get(edge.from),b=nodes.get(edge.to);if(!a||!b)return '';let path;if(a.y===b.y){const dir=b.x>a.x?1:-1;path=`M${a.x+dir*98} ${a.y+45} H${b.x-dir*100}`;}else {const x1=a.x,y1=a.y+90,x2=b.x,y2=b.y,mid=y1+(y2-y1)*.5;path=`M${x1} ${y1} V${mid} H${x2} V${y2-5}`;}return `<path d="${path}" stroke="${accent}" marker-end="url(#planArrow)"/>`;}).join('');return `<svg class="digital-plan-lines" viewBox="0 0 ${data.width} ${data.height}" aria-hidden="true"><defs><marker id="planArrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="${accent}"/></marker></defs>${lines}</svg>`+data.nodes.map(n=>`<button type="button" ${n.type==='gate'?'disabled':'data-plan-course="'+escapeHTML(n.name)+'"'} class="digital-plan-card digital-plan-${n.type}" style="left:${n.x-98}px;top:${n.y}px;--plan-accent:${accent}"><span class="digital-plan-type">${{core:'متطلب كلية',spec:'متطلب تخصص',aux:'مادة مساندة',other:'لغة',gate:'شرط الساعات'}[n.type]}</span><strong>${escapeHTML(n.name)}</strong></button>`).join('');}
