'use strict';
const http=require('http'),https=require('https'),fs=require('fs'),path=require('path');const base=__dirname;const port=Number(process.env.PORT)||8765;const cache=new Map();const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpeg':'image/jpeg','.jpg':'image/jpeg'};
const {loadPlaylist}=require('./playlist-source.cjs');const playlistCache=new Map();let lastRequest=Date.now();
const server=http.createServer((req,res)=>{lastRequest=Date.now();res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');if(req.method!=='GET'&&req.method!=='HEAD'){res.writeHead(405);res.end();return;}let url;try{url=new URL(req.url,'http://localhost')}catch{res.writeHead(400);res.end();return;}
if(url.pathname==='/api/health'){res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({site:'sanafer-it',build:'v30',root:base}));return;}
if(url.pathname==='/api/playlist'){const id=url.searchParams.get('id');if(!/^[A-Za-z0-9_-]{10,100}$/.test(id||'')){res.writeHead(400);res.end();return;}const cached=playlistCache.get(id);if(cached&&Date.now()-cached.time<3600000){res.writeHead(200,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(cached.data));return;}loadPlaylist(id).then(data=>{playlistCache.set(id,{time:Date.now(),data});res.writeHead(200,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(data))}).catch(()=>{res.writeHead(502,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify({error:'تعذر تحميل قائمة التشغيل من يوتيوب'}))});return;}
if(url.pathname==='/api/video-title'){const id=url.searchParams.get('v');if(!/^[A-Za-z0-9_-]{11}$/.test(id||'')){res.writeHead(400);res.end();return;}const send=value=>{res.writeHead(200,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(value))};if(cache.has(id)){send(cache.get(id));return;}let done=false;const upstream=https.get('https://www.youtube.com/oembed?format=json&url='+encodeURIComponent('https://www.youtube.com/watch?v='+id),{timeout:7000},response=>{let body='';if(response.statusCode!==200){done=true;res.writeHead(502);res.end();response.resume();return;}response.on('data',chunk=>{body+=chunk;if(body.length>200000)upstream.destroy()});response.on('end',()=>{if(done)return;try{const info=JSON.parse(body);if(typeof info.title!=='string')throw Error();const value={title:info.title};cache.set(id,value);done=true;send(value)}catch{done=true;res.writeHead(502);res.end();}})});upstream.on('timeout',()=>upstream.destroy());upstream.on('error',()=>{if(!done){done=true;res.writeHead(502);res.end();}});return;}
let requested;try{requested=decodeURIComponent(url.pathname)}catch{res.writeHead(400);res.end();return;}const filename=path.resolve(base,'.'+(requested==='/'?'/index.html':requested));const rel=path.relative(base,filename);if(rel.startsWith('..')||path.isAbsolute(rel)||!mime[path.extname(filename)]){res.writeHead(403);res.end();return;}fs.readFile(filename,(error,data)=>{if(error){res.writeHead(404);res.end('Not found');return;}res.writeHead(200,{'Content-Type':mime[path.extname(filename)]});res.end(req.method==='HEAD'?undefined:data)});});
server.on('error',e=>{console.error(e.code==='EADDRINUSE'?'Port 8765 is already in use. Close the earlier server or choose PORT.':e.message);process.exitCode=1});server.listen(port,'127.0.0.1',()=>console.log('Open http://127.0.0.1:'+port+' — keep this window open.'));

setInterval(()=>{if(Date.now()-lastRequest>30*60*1000)server.close(()=>process.exit(0))},60000).unref();



