function academicGrade(mark){return mark>=84?'ممتاز':mark>=76?'جيد جدًا':mark>=68?'جيد':mark>=60?'مقبول':mark>=50?'ناجح':'راسب';}
function requiredFinal(collected){return Math.max(0,50-collected);}
function weightedAverage(courses){const hours=courses.reduce((sum,c)=>sum+c.hours,0);return hours?courses.reduce((sum,c)=>sum+c.hours*c.mark,0)/hours:null;}
function cumulativeAverage(current,currentHours,previous,previousHours){return (current*currentHours+previous*previousHours)/(currentHours+previousHours);}
function initStudentCalculator(){const rows=document.querySelector('#gradeRows'),form=document.querySelector('#averageForm'),result=document.querySelector('#averageResult');let nextId=0;
function addRow(){const row=document.createElement('div');row.className='grade-course-row';const id=++nextId;row.innerHTML=`<input aria-label="اسم المادة ${id}" placeholder="اسم المادة (اختياري)" maxlength="80"><label>العلامة من 100<input type="number" class="course-mark" min="0" max="100" step="any" required inputmode="decimal"></label><label>الساعات<input type="number" class="course-hours" min="0.5" max="30" step="0.5" value="3" required inputmode="decimal"></label><button type="button" class="remove-grade-row" aria-label="حذف المادة ${id}">✕</button>`;rows.append(row);row.querySelector('button').onclick=()=>{if(rows.children.length>1){row.remove();result.textContent='';}};}
addRow();addRow();addRow();document.querySelector('#addGradeCourse').onclick=addRow;
form.addEventListener('input',()=>{result.textContent='';});form.onsubmit=e=>{e.preventDefault();if(!form.reportValidity())return;const courses=[...rows.children].map(row=>({mark:Number(row.querySelector('.course-mark').value),hours:Number(row.querySelector('.course-hours').value)}));const avg=weightedAverage(courses),hours=courses.reduce((sum,c)=>sum+c.hours,0),oldMark=document.querySelector('#previousAverage'),oldHours=document.querySelector('#previousHours');let text=`معدّلك الفصلي: ${avg.toFixed(2)} من 100 — ${academicGrade(avg)} · ${hours} ساعة`;if(oldMark.value!==''||oldHours.value!==''){if(oldMark.value===''||oldHours.value===''){result.textContent='لحساب المعدّل التراكمي، أدخل المعدّل السابق وعدد الساعات معًا.';return;}const total=cumulativeAverage(avg,hours,Number(oldMark.value),Number(oldHours.value));text+=`\nمعدّلك التراكمي: ${total.toFixed(2)} من 100 — ${academicGrade(total)}`;}result.textContent=text;};
const finalForm=document.querySelector('#finalMarkForm');finalForm.onsubmit=e=>{e.preventDefault();if(!finalForm.reportValidity())return;const collected=Number(document.querySelector('#collectedMark').value),needed=requiredFinal(collected),output=document.querySelector('#finalMarkResult');output.textContent=needed>50?`للنجاح تحتاج ${needed} من 50؛ الوصول إلى 50 غير ممكن بهذا التجميع حتى لو حصلت على العلامة الكاملة في النهائي. مجموعك الأعلى: ${collected+50} من 100.`:`تحتاج ${Number(needed.toFixed(2))} من 50 في النهائي لتصل إلى 50 من 100 وتنجح. مجموعك الأعلى إذا حصلت على 50: ${collected+50} من 100.`;};finalForm.addEventListener('input',()=>document.querySelector('#finalMarkResult').textContent='');}
document.querySelectorAll('[data-student-calc]').forEach(button=>button.addEventListener('click',()=>{const kind=button.dataset.studentCalc;openPanel(kind==='final'?'حساب علامة النجاح':'حساب المعدّل التراكمي','أدوات الطالب الجامعي',document.querySelector('#calculatorTemplate').innerHTML);$('.panel').classList.add('student-calculator-panel');const articles=[...content.querySelectorAll('.student-tool-box')];articles[0].hidden=kind!=='average';articles[1].hidden=kind!=='final';initStudentCalculator();const first=content.querySelector('.student-tool-box:not([hidden]) input');first?.focus();}));
