'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const params=new URLSearchParams(location.search),course=LESSON_LIBRARY.find(c=>c.id===params.get('course'));
let player=null,ready=false,current=0,videoItems=[],poll=null,playlistPoll=null,lastSample=null,trackedId=null,toastTimer=null,titleGeneration=0,playlistSignature='',sourcePlaylistLoaded=false;
const KEY='sanafer-watch-v1';let progress={};
try{const value=JSON.parse(localStorage.getItem(KEY)||'{}');if(value&&typeof value==='object'&&!Array.isArray(value))progress=value}catch{$('#storageNotice').textContent='حفظ التقدّم غير متاح في هذا المتصفح؛ يمكنك متابعة المشاهدة.'}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(progress))}catch{$('#storageNotice').textContent='تعذّر حفظ التقدّم. علامات هذه الجلسة ستظل ظاهرة.'}}
function watched(id){return progress[course.id]?.[id]?.done===true}
function savePosition(){if(!ready||!trackedId)return;const time=player.getCurrentTime();if(Number.isFinite(time)&&time>=0){progress[course.id]??={};progress[course.id][trackedId]??={};progress[course.id][trackedId].position=time;persist()}}
function checkSVG(){return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg>'}
function renderList(animateId){const list=$('#videoList'),focused=list.querySelector('[data-video-index]:focus')?.dataset.videoIndex;list.innerHTML=videoItems.map((v,i)=>`<button class="watch-lesson" data-video-index="${i}" aria-current="${i===current}" aria-label="${esc(v.title)}${watched(v.id)?' — تمت المشاهدة':''}"><span class="lesson-number">${String(i+1).padStart(2,'0')}</span><span class="lesson-name">${esc(v.title)}</span><span class="lesson-done ${watched(v.id)?'completed':''} ${animateId===v.id?'animate':''}">${watched(v.id)?checkSVG():''}</span></button>`).join('');if(focused!==undefined)list.querySelector(`[data-video-index="${focused}"]`)?.focus();const done=videoItems.filter(v=>watched(v.id)).length,percent=videoItems.length?Math.round(done/videoItems.length*100):0;$('#progressText').textContent=`${done}/${videoItems.length} · ${percent}٪`;$('#courseProgress').value=percent;$('#lessonCount').textContent=`${videoItems.length} فيديو`;$('#previousVideo').disabled=current===0;$('#nextVideo').disabled=current>=videoItems.length-1;$('#manualComplete').disabled=!videoItems.length;$('#manualComplete').textContent=watched(videoItems[current]?.id)?'تمت مشاهدة الدرس ✓':'تحديد كمشاهد ✓';}
function markDone(id){if(!videoItems.some(v=>v.id===id)||watched(id))return;progress[course.id]??={};progress[course.id][id]??={};progress[course.id][id].done=true;progress[course.id][id].position=0;persist();renderList(id);$('#completionToast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#completionToast').hidden=true,3000)}
function activeId(){try{return new URL(player.getVideoUrl()).searchParams.get('v')}catch{return videoItems[current]?.id}}
function syncCurrent(){const id=activeId(),index=videoItems.findIndex(v=>v.id===id);if(index<0)return;if(id!==trackedId){lastSample=null;trackedId=id;}if(index!==current){current=index;renderList();}$('#videoTitle').textContent=videoItems[current].title;$('#youtubeLink').href='https://www.youtube.com/watch?v='+id;}
function selectVideo(i){if(!Number.isInteger(i)||i<0||i>=videoItems.length)return;savePosition();delete $('#watchStatus').dataset.error;$('#youtubeLink').classList.remove('youtube-fallback');current=i;trackedId=videoItems[i].id;lastSample=null;renderList();$('#videoTitle').textContent=videoItems[i].title;$('#youtubeLink').href='https://www.youtube.com/watch?v='+trackedId;if(!ready){const target=new URL('https://www.youtube.com/embed/'+trackedId);target.searchParams.set('enablejsapi','1');target.searchParams.set('playsinline','1');target.searchParams.set('autoplay','1');if(location.protocol!=='file:')target.searchParams.set('origin',location.origin);$('#youtubePlayer').src=target.href;return;}if(course.playlistId&&!sourcePlaylistLoaded)player.playVideoAt(i);else player.loadVideoById(trackedId);}
function sample(){if(!ready)return;syncCurrent();const id=trackedId;if(!id||player.getPlayerState()!==1){lastSample=null;return;}const t=player.getCurrentTime(),duration=player.getDuration();if(!Number.isFinite(t)||!Number.isFinite(duration)||duration<=0)return;progress[course.id]??={};const record=progress[course.id][id]??={};record.ranges??=[];if(lastSample&&lastSample.id===id){const delta=t-lastSample.time;if(delta>0&&delta<=2.5){record.ranges.push([lastSample.time,t]);record.ranges.sort((a,b)=>a[0]-b[0]);const merged=[];for(const r of record.ranges){const tail=merged[merged.length-1];if(tail&&r[0]<=tail[1]+.05)tail[1]=Math.max(tail[1],r[1]);else merged.push(r)}record.ranges=merged;const seconds=merged.reduce((sum,r)=>sum+Math.max(0,Math.min(duration,r[1])-Math.max(0,r[0])),0);if(seconds/duration>=.9)markDone(id)}}record.position=t;lastSample={id,time:t};}
async function getTitle(item,generation){try{let response=await fetch('/api/video-title?v='+encodeURIComponent(item.id));if(!response.ok)throw Error();let info=await response.json();if(typeof info.title!=='string')throw Error();if(generation!==titleGeneration)return;item.title=info.title;renderList();syncCurrent()}catch{try{const response=await fetch('https://www.youtube.com/oembed?format=json&url='+encodeURIComponent('https://www.youtube.com/watch?v='+item.id));if(!response.ok)return;const info=await response.json();if(generation!==titleGeneration||typeof info.title!=='string')return;item.title=info.title;renderList();syncCurrent()}catch{/* Numbered lessons retain the real playlist order if title retrieval is unavailable. */}}}
function hydrateTitles(){const generation=++titleGeneration;let cursor=0;async function worker(){while(cursor<videoItems.length){const item=videoItems[cursor++];await getTitle(item,generation)}}for(let i=0;i<3;i++)worker();}
function adoptPlaylist(){if(!course.playlistId||!ready||sourcePlaylistLoaded)return;const ids=player.getPlaylist();if(!Array.isArray(ids)||!ids.length)return;const valid=ids.filter(id=>/^[A-Za-z0-9_-]{11}$/.test(id));if(!valid.length)return;clearInterval(playlistPoll);const signature=valid.join(',');if(signature===playlistSignature)return;playlistSignature=signature;videoItems=valid.map((id,i)=>({id,title:`الدرس ${i+1}`}));current=Math.max(0,player.getPlaylistIndex());trackedId=videoItems[current]?.id;$('#listHeading').textContent='قائمة التشغيل';$('#listNote').textContent='الدروس مرتبة كما وضعها صاحب قائمة التشغيل. تُحمّل العناوين الأصلية عند توفرها.';renderList();syncCurrent();hydrateTitles();}
function onReady(event){player=event.target;ready=true;$('#watchStatus').textContent='المشغل جاهز. اضغط تشغيل لبدء الدرس.';renderList();if(course.playlistId){adoptPlaylist();let attempts=0;playlistPoll=setInterval(()=>{adoptPlaylist();if(++attempts>=15){clearInterval(playlistPoll);if(!videoItems.length){$('#watchStatus').textContent='تعذّر تحميل قائمة التشغيل؛ يمكنك فتحها على يوتيوب.';$('#manualComplete').disabled=true;}}},1000);}else{syncCurrent();hydrateTitles();const saved=progress[course.id]?.[videoItems[0].id];if(saved?.position>5&&!saved.done)player.seekTo(saved.position,true);}poll=setInterval(sample,1000);}
function onState(event){if(!ready)return;if(event.data===0){sample();savePosition();}else if(event.data===1||event.data===5){adoptPlaylist();syncCurrent();renderList();}else{sample();savePosition();}}
function onError(event){lastSample=null;const status=$('#watchStatus');status.dataset.error=String(event.data);status.textContent=[101,150].includes(event.data)?'صاحب الفيديو يمنع عرضه داخل المواقع. المادة باقية؛ شاهد هذا الدرس على يوتيوب أو اختر درسًا آخر.':event.data===100?'هذا الفيديو محذوف أو خاص. جرّب درسًا آخر أو افتح رابط المصدر.':event.data===153?'تعذّر تعريف رابط الموقع لدى يوتيوب. شغّل الموقع عبر رابط ويب وتأكد من السماح بإرسال مرجع الصفحة.':'تعذّر تشغيل هذا الفيديو الآن. جرّب درسًا آخر أو شاهده على يوتيوب.';$('#youtubeLink').classList.add('youtube-fallback');}

function createPlayer(){if(!course||player)return;player=new YT.Player('youtubePlayer',{events:{onReady,onStateChange:onState,onError,onAutoplayBlocked:()=>$('#watchStatus').textContent='اضغط زر التشغيل داخل الفيديو لبدء المشاهدة.'}});}
window.onYouTubeIframeAPIReady=createPlayer;
if(!course){$('#courseTitle').textContent='المادة غير موجودة';$('#watchStatus').textContent='ارجع إلى قسم الشروحات واختر مادة.';$('#manualComplete').disabled=true;}else{document.body.style.setProperty('--watch-accent','#72d9f2');document.body.style.setProperty('--watch-wash','rgba(114,217,242,.12)');$('#courseTitle').textContent=course.name;document.title=course.name+' | شروحات سنافر IT';$('#courseNote').textContent=course.note;$('#youtubeLink').href=course.url;if(course.playlistId){videoItems=course.videos.map(v=>({...v}));$('#listHeading').textContent='الفيديوهات المتاحة';$('#playlistLink').href='https://www.youtube.com/playlist?list='+course.playlistId;$('#playlistLink').hidden=false;$('#listNote').textContent='هذا الفيديو متاح الآن. جارٍ تحميل بقية قائمة التشغيل بترتيبها الأصلي…';}else{videoItems=course.videos.map(v=>({...v}));$('#listHeading').textContent='الفيديوهات المتاحة';$('#listNote').textContent='هذه الفيديوهات التي تحققنا منها؛ لا تمثل قائمة تشغيل كاملة.';}renderList();const embed=new URL('https://www.youtube.com/embed/'+videoItems[0].id);embed.searchParams.set('enablejsapi','1');embed.searchParams.set('playsinline','1');embed.searchParams.set('rel','0');embed.searchParams.set('autoplay','1');if(course.playlistId)embed.searchParams.set('list',course.playlistId);if(location.protocol!=='file:')embed.searchParams.set('origin',location.origin);$('#youtubePlayer').src=embed.href;$('#watchStatus').textContent='الشرح جاهز داخل الإطار. إذا لم يبدأ تلقائيًا اضغط زر التشغيل داخل الفيديو.';const api=document.createElement('script');api.src='https://www.youtube.com/iframe_api';api.onerror=()=>$('#watchStatus').textContent='يمكنك المشاهدة داخل الإطار؛ متابعة التقدم التلقائية غير متاحة الآن.';document.head.appendChild(api);if(course.playlistId)loadIndependentPlaylist();setTimeout(()=>{if(!ready)$('#watchStatus').textContent='المشغل داخل الإطار مستقل عن متابعة التقدم. إذا ظهرت رسالة من يوتيوب، تحقق من اتصال الإنترنت وتشغيل الموقع عبر رابط ويب.'},15000);}
$('#videoList').addEventListener('click',e=>{const b=e.target.closest('[data-video-index]');if(b)selectVideo(Number(b.dataset.videoIndex))});$('#previousVideo').onclick=()=>selectVideo(current-1);$('#nextVideo').onclick=()=>selectVideo(current+1);$('#manualComplete').onclick=()=>{const item=videoItems[current];if(item)markDone(item.id)};window.addEventListener('pagehide',()=>{savePosition();persist();clearInterval(poll);clearInterval(playlistPoll)});document.addEventListener('visibilitychange',()=>{if(document.hidden){savePosition();lastSample=null;}});

async function loadIndependentPlaylist(){if(location.protocol==='file:'){$('#listNote').textContent='الفيديو المتحقق منه ظاهر. افتح «افتح الموقع.cmd» لتحميل قائمة التشغيل ومشاهدة الفيديو داخل الموقع.';return;}try{const response=await fetch('/api/playlist?id='+encodeURIComponent(course.playlistId));if(!response.ok)throw Error();const data=await response.json();if(!Array.isArray(data.videos)||!data.videos.length||data.videos.some(v=>!/^[A-Za-z0-9_-]{11}$/.test(v.id)||typeof v.title!=='string'))throw Error();const previousId=trackedId||videoItems[current]?.id;videoItems=data.videos.map(v=>({id:v.id,title:v.title}));sourcePlaylistLoaded=true;current=Math.max(0,videoItems.findIndex(v=>v.id===previousId));$('#listHeading').textContent='قائمة التشغيل';$('#listNote').textContent=data.complete?'الدروس بعناوينها الأصلية وبتسلسل صاحب القائمة على يوتيوب.':'تم تحميل جزء من القائمة؛ يمكنك الاطلاع على القائمة الأصلية كاملة عبر رابطها.';renderList();if(!videoItems.some(v=>v.id===previousId))selectVideo(0);}catch{$('#listNote').textContent='تعذّر تحميل بقية قائمة التشغيل. الفيديوهات المتحققة ظاهرة، ويمكن المحاولة مجددًا.';$('#retryPlaylist').hidden=false;}}
$('#retryPlaylist').onclick=()=>{$('#retryPlaylist').hidden=true;loadIndependentPlaylist()};
if(location.protocol!=='file:')setInterval(()=>fetch('/api/health').catch(()=>{}),60000);

$('#localFileNotice').hidden=location.protocol!=='file:';
